version: '3.1'

services:
  web:
    container_name: publication-app
    build: .  
    ports:
      - 3000:3000
    links:
      - mongo
    networks:
      - mongo-compose-network    
  mongo-express:
    container_name: mongo-client
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: hpaiva
      ME_CONFIG_BASICAUTH_PASSWORD: Hpaiva2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo2019
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongo-database
    image: mongo
    environment:
      MONGO_INITDB_USERNAME: admin
    ports:
      - "27017:27017"
    volumes:
      - /hpaiva/workspace_personal/publication-server/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge